[package]
name = "srelens-kube"
version.workspace = true
edition.workspace = true

[dependencies]
srelens-capability = { path = "../capability" }
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
schemars = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["fs", "time", "net", "io-util", "process"] }
kube = { version = "0.96", default-features = false, features = ["client", "config", "rustls-tls", "runtime", "ws"] }
k8s-openapi = { version = "0.23", features = ["latest"] }
futures = "0.3"
base64 = "0.22"
flate2 = "1"
http = "1"
similar = "2"
sha2 = "0.10"
hex = "0.4"
tar = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tempfile = "3"
