// The capability catalog, read rather than retyped.
//
// `packages/core/src/lib/capability-catalog.json` is a projection of the live
// backend registry, generated by `catalog_of` (`crates/registry/src/catalog.rs`)
// and held equal to it by `capability_catalog_json_is_in_sync`
// (`crates/registry/src/lib.rs`) — a Rust test that fails the build when the
// committed file drifts. That is what makes this file a source of truth rather
// than a second copy: a capability added, renamed or re-annotated in Rust
// cannot ship without this JSON changing with it.
//
// It exists because the frontend must not link Rust. The palette audit
// (`paletteActions.audit.test.ts`) already read it; Settings now needs the same
// facts at runtime, to say which capabilities an agent can never call without
// a confirmation.
import catalog from "./capability-catalog.json";

/** One capability, as the backend registry annotates it. */
export interface CapabilityFacts {
  /** The id an agent calls and the audit trail records, e.g. `k8s.drainNode`. */
  id: string;
  /** Changes nothing. */
  readOnly: boolean;
  /** Destroys or disrupts something, as opposed to merely changing it. */
  destructive: boolean;
  /**
   * Execution stops at a consent step. THE flag that gates a call
   * (`McpServer::requires_confirm`), and not derivable from the other two: a
   * `SENSITIVE_READ` is read-only, non-destructive and gated, and a `MUTATING`
   * capability is neither read-only nor destructive and is gated too.
   */
  requiresConfirm: boolean;
}

/** Every capability the backend registers, sorted by id. */
export const CAPABILITY_CATALOG: readonly CapabilityFacts[] = catalog;

/**
 * The two ids the catalog carries that a WEB registry does not register.
 *
 * The committed catalog projects `build_registry()` — the desktop/MCP registry,
 * which includes the durable desktop settings surface. A web server builds its
 * registry through `build_registry_with_paths`, which passes no settings path,
 * because web settings are per-user SQLite rows rather than a file on the host;
 * `web_registry_omits_host_desktop_settings` (`crates/registry/src/lib.rs`)
 * pins exactly these two ids as the difference.
 *
 * Named here so a count shown to a reader is a count of what THEIR build
 * registers. Off by one is a small error, and shipping a small error while
 * fixing a large one is how the large one came to be.
 */
export const HOST_ONLY_CAPABILITY_IDS: readonly string[] = ["settings.get", "settings.set"];

/**
 * Every capability that cannot run without a confirmation, sorted by id.
 *
 * Two kinds are in here and both belong: anything that changes something (an
 * invariant, not a policy — `assert_mutating_capabilities_are_gated` in
 * `crates/mcp/src/completeness.rs` fails the build if a non-read-only
 * capability is registered ungated), and the read that returns Secret values,
 * which is gated despite changing nothing.
 *
 * `host` decides whether the desktop-only settings capabilities count, and it
 * is REQUIRED rather than defaulted from `isTauri()` here. A default read
 * inside this module would be read inside this module — a caller's mocked
 * `isTauri` could not reach it, so a test would silently exercise the other
 * branch from the one it thought it had chosen. The caller knows which host it
 * is; it says so.
 */
export function gatedCapabilityIds(host: "desktop" | "web"): string[] {
  return CAPABILITY_CATALOG.filter(
    (c) => c.requiresConfirm && (host === "desktop" || !HOST_ONLY_CAPABILITY_IDS.includes(c.id)),
  ).map((c) => c.id);
}
