import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
vi.mock("@srelens/core", async (original) => ({ ...(await original<typeof import("@srelens/core")>()), listExtensionCatalog: vi.fn(), reviewCatalogExtension: vi.fn(), openExternal: vi.fn() }));
import { listExtensionCatalog, reviewCatalogExtension, openExternal } from "@srelens/core";
import { ExtensionCatalog } from "./ExtensionCatalog";
const entry = { id: "org.srelens.flux", name: "Flux", description: "Flux resources", repository: "https://github.com/srelens/extension-flux", license: "MIT", release: { version: "0.2.0", sha256: "abc", srelensApiVersion: "^0.1", prerelease: true } };
const snapshot = { catalog: { extensions: [entry] }, fetchedAt: 1, stale: false, error: null, hostApiVersion: "0.1.0", incompatible: [] };
beforeEach(() => { vi.resetAllMocks(); vi.mocked(listExtensionCatalog).mockResolvedValue(snapshot as any); });
it("browses on demand, searches, and reviews exact verified bytes before any install", async () => {
  const review = vi.fn();
  vi.mocked(reviewCatalogExtension).mockResolvedValue({ manifest: '{"name":"Flux","permissions":[]}' });
  render(<ExtensionCatalog developerMode onReview={review} installed={[]} />);
  expect(listExtensionCatalog).not.toHaveBeenCalled();
  fireEvent.click(screen.getByText("Browse catalog"));
  expect(await screen.findByText("Flux")).toBeTruthy();
  expect(screen.getByText(/Preview/)).toBeTruthy();
  fireEvent.change(screen.getByLabelText("Find an extension"), { target: { value: "argo" } });
  expect(screen.getByText("No matching extensions.")).toBeTruthy();
  fireEvent.change(screen.getByLabelText("Find an extension"), { target: { value: "flux" } });
  fireEvent.click(screen.getByText("Review installation"));
  await waitFor(() => expect(review).toHaveBeenCalledWith('{"name":"Flux","permissions":[]}'));
  expect(reviewCatalogExtension).toHaveBeenCalledWith(entry.id, "abc");
});
it("shows cached refresh failures and keeps incompatible releases disabled", async () => {
  vi.mocked(listExtensionCatalog).mockResolvedValue({ ...snapshot, stale: true, error: "offline", incompatible: [entry.id] } as any);
  render(<ExtensionCatalog developerMode onReview={vi.fn()} installed={[]} />);
  fireEvent.click(screen.getByText("Browse catalog"));
  expect(await screen.findByText(/offline/)).toBeTruthy();
  expect((screen.getByText("Review installation") as HTMLButtonElement).disabled).toBe(true);
  fireEvent.click(screen.getByText("Refresh catalog"));
  await waitFor(() => expect(listExtensionCatalog).toHaveBeenLastCalledWith(true));
});
it("surfaces download and browser errors and requires developer mode", async () => {
  const { rerender } = render(<ExtensionCatalog developerMode={false} onReview={vi.fn()} installed={[]} />);
  fireEvent.click(screen.getByText("Browse catalog"));
  await screen.findByText("Flux");
  expect((screen.getByText("Review installation") as HTMLButtonElement).disabled).toBe(true);
  rerender(<ExtensionCatalog developerMode onReview={vi.fn()} installed={[]} />);
  vi.mocked(reviewCatalogExtension).mockRejectedValue(new Error("checksum mismatch"));
  fireEvent.click(screen.getByText("Review installation"));
  expect(await screen.findByText("checksum mismatch")).toBeTruthy();
  vi.mocked(openExternal).mockRejectedValue(new Error("browser unavailable"));
  fireEvent.click(screen.getByText("Repository"));
  expect(await screen.findByText("browser unavailable")).toBeTruthy();
});
it("reports a first-load failure with retry, not an empty catalog", async () => {
  vi.mocked(listExtensionCatalog).mockRejectedValueOnce(new Error("offline"));
  render(<ExtensionCatalog developerMode onReview={vi.fn()} installed={[]} />);
  fireEvent.click(screen.getByText("Browse catalog"));
  expect(await screen.findByText("offline")).toBeTruthy();
  expect(screen.queryByText("No matching extensions.")).toBeNull();
  fireEvent.click(screen.getByText("Browse catalog"));
  expect(await screen.findByText("Flux")).toBeTruthy();
});
