import React from "react";
import {
  ArrowLeftRight,
  BellRing,
  Box,
  BriefcaseBusiness,
  Circle,
  Clock3,
  Copy,
  Cpu,
  Database,
  FileCog,
  FilePlus2,
  FolderTree,
  Gauge,
  GitBranch,
  HardDrive,
  KeyRound,
  Layers3,
  LayoutDashboard,
  ListOrdered,
  Network,
  RadioTower,
  Route,
  Scaling,
  Server,
  ServerCog,
  Settings,
  Wrench,
  Shield,
  ShieldCheck,
  ShipWheel,
  Signpost,
  SlidersHorizontal,
  TimerReset,
  UserRoundCheck,
  UserRoundCog,
  Webhook,
  type LucideIcon,
} from "lucide-react";

const RESOURCE_ICONS: Record<string, LucideIcon> = {
  overview: LayoutDashboard,
  nodes: Server,
  namespaces: FolderTree,
  events: BellRing,
  pods: Box,
  deployments: Layers3,
  statefulsets: Database,
  daemonsets: ServerCog,
  replicasets: Copy,
  jobs: BriefcaseBusiness,
  cronjobs: Clock3,
  configmaps: FileCog,
  secrets: KeyRound,
  resourcequotas: Gauge,
  limitranges: SlidersHorizontal,
  horizontalpodautoscalers: Scaling,
  poddisruptionbudgets: ShieldCheck,
  priorityclasses: ListOrdered,
  runtimeclasses: Cpu,
  leases: TimerReset,
  mutatingwebhookconfigurations: Webhook,
  validatingwebhookconfigurations: Webhook,
  services: Network,
  endpoints: RadioTower,
  endpointslices: GitBranch,
  ingresses: Route,
  ingressclasses: Signpost,
  networkpolicies: Shield,
  portforwards: ArrowLeftRight,
  persistentvolumeclaims: HardDrive,
  persistentvolumes: Database,
  storageclasses: Layers3,
  serviceaccounts: UserRoundCog,
  clusterroles: Shield,
  roles: ShieldCheck,
  clusterrolebindings: UserRoundCheck,
  rolebindings: UserRoundCheck,
  helmreleases: ShipWheel,
  settings: Settings,
  toolbox: Wrench,
  newresource: FilePlus2,
};

export function iconForResourceKind(kind: string): LucideIcon {
  return RESOURCE_ICONS[kind] ?? Circle;
}

/** Small monochrome Lucide icon for a resource navigation item. */
export function NavIcon({ icon: Icon }: { icon: LucideIcon }) {
  return <Icon className="fl-nav__icon" aria-hidden="true" />;
}
