// Code generated by sdk/go/internal/gen from schemas/sidecar-protocol.v0.1.json. DO NOT EDIT.

package protocol

import (
	"encoding/json"
	"regexp"
)

// APIVersion is the sidecar API version this file was generated for.
const APIVersion = "0.1.0"

// MaxMessageBytes is the longest line either side may write, not counting its line ending.
const MaxMessageBytes = 4194304

// The JSON-RPC error codes the protocol uses.
const (
	CodeCapabilityFailed      = -32003
	CodeConsentDenied         = -32002
	CodeInternalError         = -32603
	CodeInvalidParams         = -32602
	CodeInvalidRequest        = -32600
	CodeMethodNotFound        = -32601
	CodeParseError            = -32700
	CodeRequestCancelled      = -32800
	CodeUnsupportedAPIVersion = -32001
)

// The protocol's methods.
const (
	MethodCancelRequest = "$/cancelRequest"
	MethodActivate      = "activate"
	MethodDeactivate    = "deactivate"
	MethodHealth        = "health"
	MethodHostAction    = "host/action"
	MethodHostRead      = "host/read"
	MethodHostResource  = "host/resource"
	MethodInitialize    = "initialize"
	MethodShutdown      = "shutdown"
	MethodStreamCancel  = "stream/cancel"
	MethodStreamClose   = "stream/close"
	MethodStreamData    = "stream/data"
	MethodStreamError   = "stream/error"
	MethodStreamOpen    = "stream/open"
)

// MethodDirections is who sends each method: "hostToSidecar", "sidecarToHost" or "both".
var MethodDirections = map[string]string{
	"$/cancelRequest": "both",
	"activate":        "hostToSidecar",
	"deactivate":      "hostToSidecar",
	"health":          "hostToSidecar",
	"host/action":     "sidecarToHost",
	"host/read":       "sidecarToHost",
	"host/resource":   "sidecarToHost",
	"initialize":      "hostToSidecar",
	"shutdown":        "hostToSidecar",
	"stream/cancel":   "hostToSidecar",
	"stream/close":    "sidecarToHost",
	"stream/data":     "sidecarToHost",
	"stream/error":    "sidecarToHost",
	"stream/open":     "hostToSidecar",
}

// CallContext: The cluster and namespace one call names. Every call from a sidecar carries one: srelens has no current cluster to assume.
type CallContext struct {
	// A cluster as srelens names it: the `context` of the request the sidecar is serving, a kubeconfig context's stable ID, pinned ID or name. At most 4096 bytes as UTF-8, and not blank.
	ClusterID string `json:"clusterId"`
	// A namespace, or null for every namespace or a cluster-scoped kind. Required, though it may be null: "no namespace" is said, not assumed.
	Namespace *string `json:"namespace"`
}

// CancelParams: `$/cancelRequest`'s params: stop working on request `id`.
type CancelParams struct {
	ID RequestID `json:"id"`
}

// Empty: The params and result of `activate`, `health`, `deactivate` and `shutdown`: `{}`.
type Empty struct {
}

// HostActionParams: `host/action`'s params: run one of the app's declared actions on object `name`, as read (`uid`, `resourceVersion`), once a person has confirmed it.
type HostActionParams struct {
	Action          string      `json:"action"`
	Capability      string      `json:"capability"`
	Context         CallContext `json:"context"`
	Name            string      `json:"name"`
	ResourceVersion string      `json:"resourceVersion"`
	UID             string      `json:"uid"`
}

// HostReadParams: `host/read`'s params: read one of the app's declared readers, or one of its `network.http` requests.
type HostReadParams struct {
	Capability string      `json:"capability"`
	Context    CallContext `json:"context"`
}

// HostResourceParams: `host/resource`'s params: inspect object `name` of a declared custom-resource reader.
type HostResourceParams struct {
	Capability string      `json:"capability"`
	Context    CallContext `json:"context"`
	Name       string      `json:"name"`
}

// InitializeLimits: The limits a sidecar runs under, so an SDK can hold itself to them.
type InitializeLimits struct {
	// The CPU limit the sandbox enforces, in CPUs.
	CPUs float64 `json:"cpus"`
	// The data directory's size limit, in bytes.
	DataBytes uint64 `json:"dataBytes"`
	// The data directory's limit on files, directories and links.
	DataEntries uint64 `json:"dataEntries"`
	// Requests srelens has in flight at once; the next is refused, not queued.
	MaxConcurrentRequests uint64 `json:"maxConcurrentRequests"`
	// Streams open at once.
	MaxStreams uint64 `json:"maxStreams"`
	// The memory limit the sandbox enforces, in bytes.
	MemoryBytes uint64 `json:"memoryBytes"`
	// How long srelens waits for the answer to one request, in milliseconds.
	RequestTimeoutMs uint64 `json:"requestTimeoutMs"`
}

// InitializeParams: `initialize`'s params: every sidecar API version srelens speaks, the limits in force, and the one directory the sidecar may write.
type InitializeParams struct {
	// Every sidecar API version srelens speaks, oldest first.
	APIVersions []string `json:"apiVersions"`
	// The data directory: the one path the sidecar may write, and its working directory.
	DataDirectory string           `json:"dataDirectory"`
	Host          Peer             `json:"host"`
	Limits        InitializeLimits `json:"limits"`
}

// InitializeResult: A sidecar's answer to `initialize`.
type InitializeResult struct {
	// The version it chose, one of those offered.
	APIVersion string `json:"apiVersion"`
	Sidecar    *Peer  `json:"sidecar,omitempty"`
}

// Peer: One end of the conversation: srelens, or the sidecar.
type Peer struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// RPCError: A JSON-RPC error object.
type RPCError struct {
	Code    int64           `json:"code"`
	Data    json.RawMessage `json:"data,omitempty"`
	Message string          `json:"message"`
}

// StreamCancelParams: `stream/cancel`'s params: stop sending stream `stream`.
type StreamCancelParams struct {
	Stream uint64 `json:"stream"`
}

// StreamCloseParams: `stream/close`'s params: stream `stream` ended.
type StreamCloseParams struct {
	Stream uint64 `json:"stream"`
}

// StreamDataParams: `stream/data`'s params: one frame of stream `stream`.
type StreamDataParams struct {
	Data   json.RawMessage `json:"data"`
	Stream uint64          `json:"stream"`
}

// StreamErrorParams: `stream/error`'s params: stream `stream` failed.
type StreamErrorParams struct {
	Message string `json:"message"`
	Stream  uint64 `json:"stream"`
}

// StreamOpenParams: `stream/open`'s params: open stream `stream`, streaming `method`.
type StreamOpenParams struct {
	Method string          `json:"method"`
	Params json.RawMessage `json:"params"`
	// The id srelens chose; every frame of the stream carries it.
	Stream uint64 `json:"stream"`
}

// UnsupportedAPIVersion: The `data` of error -32001, the answer to `initialize` from a sidecar that speaks none of the offered versions.
type UnsupportedAPIVersion struct {
	// The versions it does speak.
	Supported []string `json:"supported"`
}

// fieldShapes are the rules the schema states for each patterned string field, keyed "Definition.property".
var fieldShapes = map[string]fieldShape{
	"CallContext.clusterId":            {pattern: regexp.MustCompile("[^\t\n\v\f\r \u0085\u00a0\u1680\u2000-\u200a\u2028\u2029\u202f\u205f\u3000]"), maxLength: 4096, not: []string(nil)},
	"CallContext.namespace":            {pattern: regexp.MustCompile("^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$"), maxLength: 63, not: []string(nil)},
	"HostActionParams.action":          {pattern: regexp.MustCompile("^[A-Za-z0-9-]{1,64}$"), maxLength: 64, not: []string(nil)},
	"HostActionParams.capability":      {pattern: regexp.MustCompile("^[A-Za-z0-9-]{1,64}$"), maxLength: 64, not: []string(nil)},
	"HostActionParams.name":            {pattern: regexp.MustCompile("^[A-Za-z0-9.-]{1,253}$"), maxLength: 253, not: []string{".", ".."}},
	"HostActionParams.resourceVersion": {pattern: regexp.MustCompile("^[!-~]{1,128}$"), maxLength: 128, not: []string(nil)},
	"HostActionParams.uid":             {pattern: regexp.MustCompile("^[!-~]{1,128}$"), maxLength: 128, not: []string(nil)},
	"HostReadParams.capability":        {pattern: regexp.MustCompile("^[A-Za-z0-9-]{1,64}$"), maxLength: 64, not: []string(nil)},
	"HostResourceParams.capability":    {pattern: regexp.MustCompile("^[A-Za-z0-9-]{1,64}$"), maxLength: 64, not: []string(nil)},
	"HostResourceParams.name":          {pattern: regexp.MustCompile("^[A-Za-z0-9.-]{1,253}$"), maxLength: 253, not: []string{".", ".."}},
}

// fieldShape is one string field's rule: at most maxLength bytes, matching pattern, and none of not.
type fieldShape struct {
	pattern   *regexp.Regexp
	maxLength int
	not       []string
}
